const fs = require('fs');
const lines = [];
lines.push("import React, { useState, useRef, useCallback } from 'react';");
lines.push("import { View, Text, Modal, TouchableOpacity, TouchableWithoutFeedback, StyleSheet, FlatList, Animated } from 'react-native';");
lines.push("import { useSafeAreaInsets } from 'react-native-safe-area-context';");
lines.push("import { T } from './TranslatedText';");
lines.push("");
lines.push("let ExpoAudio = null;");
lines.push("try { ExpoAudio = require('expo-audio'); } catch (_) {}");
lines.push("");
lines.push("const SOUND_EFFECTS = [");
lines.push("  { id: 'cheer',   label: 'Cheer',     emoji: '\uD83C\uDF89', color: '#F59E0B', uri: 'https://www.soundjay.com/human/sounds/applause-01.mp3' },");
lines.push("  { id: 'clap',    label: 'Clap',      emoji: '\uD83D\uDC4F', color: '#3B82F6', uri: 'https://www.soundjay.com/human/sounds/applause-8.mp3' },");
lines.push("  { id: 'win',     label: 'Win',       emoji: '\uD83C\uDFC6', color: '#EAB308', uri: 'https://www.soundjay.com/misc/sounds/bell-ringing-01.mp3' },");
lines.push("  { id: 'awkward', label: 'Awkward',   emoji: '\uD83D\uDE2C', color: '#8B5CF6', uri: 'https://www.soundjay.com/misc/sounds/fail-buzzer-01.mp3' },");
lines.push("  { id: 'laugh',   label: 'Laugh',     emoji: '\uD83D\uDE02', color: '#22C55E', uri: 'https://www.soundjay.com/human/sounds/laughing-1.mp3' },");
lines.push("  { id: 'boo',     label: 'Mock',      emoji: '\uD83D\uDC4E', color: '#EF4444', uri: 'https://www.soundjay.com/human/sounds/boo-01.mp3' },");
lines.push("  { id: 'horror',  label: 'Horror',    emoji: '\uD83D\uDC7B', color: '#6B7280', uri: 'https://www.soundjay.com/horror/sounds/horror-atmosphere-01.mp3' },");
lines.push("  { id: 'drum',    label: 'Drum Roll', emoji: '\uD83E\uDD41', color: '#F97316', uri: 'https://www.soundjay.com/misc/sounds/drum-roll-1.mp3' },");
lines.push("  { id: 'love',    label: 'Love',      emoji: '\u2764\uFE0F', color: '#EC4899', uri: 'https://www.soundjay.com/misc/sounds/kiss-1.mp3' },");
lines.push("  { id: 'wow',     label: 'Wow',       emoji: '\uD83D\uDE2E', color: '#06B6D4', uri: 'https://www.soundjay.com/human/sounds/crowd-gasp-1.mp3' },");
lines.push("];");
lines.push("const AUTO_STOP_MS = 3500;");
fs.writeFileSync('e:/NodeApp/mobile/src/components/SoundEffectsModal.js', lines.join('\n'), {encoding:'utf8'});
console.log('header written: ' + lines.length + ' lines');
