import React, { createContext, useContext, useState, useEffect, useRef } from 'react';
import {
  Modal,
  View,
  Text,
  TouchableOpacity,
  FlatList,
  TextInput,
  StyleSheet,
  Platform,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import api from '../api/client';

export const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
];

// Pure RAM Cache (0 bytes stored on user's phone disk)
const ramCache = new Map();
ramCache.set('hi:::followed you, click here to follow them back and become new friends! 👏', 'ने आप को फॉलो किया, यहाँ क्लिक से उसको भी फॉलो करें, नया दोस्तों बनें!👏');
ramCache.set('hi:::Chat', 'Chat');
ramCache.set('hi:::Followers', 'Followers');
ramCache.set('hi:::1 days ago', '1 days ago');

const LanguageContext = createContext();

// Detect device system language
const detectDeviceLanguage = () => {
  try {
    const locale =
      Intl?.DateTimeFormat?.()?.resolvedOptions?.()?.locale ||
      (typeof navigator !== 'undefined' && (navigator.language || navigator.userLanguage)) ||
      'en';
    const code = locale.split(/[-_]/)[0].toLowerCase();
    const matched = LANGUAGES.find((l) => l.code === code);
    return matched ? matched.code : 'en';
  } catch (e) {
    return 'en';
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');
  // Live RAM translations (Zero phone disk storage)
  const [liveTranslations, setLiveTranslations] = useState({});
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [refreshTrigger, setRefreshTrigger] = useState(0);

  // Dynamic set of all phrases used in the app (auto-accumulated at runtime)
  const knownPhrases = useRef(
    new Set([
      'Voice Chat, Play Games, Make Friends',
      'Sexual and violent contents are not allowed. All violators will be banned. Please report and do not expose personal info.',
      'Basic tools',
      'Entertainment tools',
      'Other tools',
      'Personal Tasks',
      'Daily Sign in',
      'Send comments in the room',
      'Seated for 5 minutes',
      'Follow 1 people in chatroom',
      'Share 1 chatroom',
      'Finished recharge',
      'Stay in the room for 5 minutes',
      'Like 5 posts from others',
      'Current Diamonds Balance:',
      'Awesome!',
      'Diamonds added to your wallet',
      'Loading tasks...',
      'Refreshes every day at 00:00',
      'View & Edit Profile',
      'Followers',
      'Following',
      'Gifts',
      'Received',
      'Visitors',
      'Visitors within 15 days',
      'Mutual Followed',
      'No followers yet',
      'Not following anyone yet',
      'No visitors within the last 15 days',
      'Unfollow',
      'Games Coming Soon',
      'Exciting mini-games will be available here soon',
      'Wallet',
      'VIP/SVIP',
      'Subscription',
      'Noble',
      'Activate',
      'If direct link shows security decline, simply copy UPI ID below, paste it in PhonePe/GPay to pay, then enter the 12-digit UTR.',
      'Official UPI ID',
      'Copy UPI ID',
      'Copied!',
      'Copy UPI ID & Open Payment App:',
      'UPI ID copied to clipboard: ',
      'Official Payment Mobile Number',
      'Copy Mobile Number',
      'Mobile number copied: ',
      '. Paste in "To Mobile Number" in PhonePe/Paytm to pay.',
      'Pay via Mobile Number (Zero Error & Fast)',
      'Open PhonePe or Paytm, select "To Mobile Number", paste 7982720270, and pay. Then enter UTR below.',
      'Scan & Pay via UPI QR Code',
      'Scan using any UPI app (PhonePe, GPay, Paytm) to complete payment',
      'Download QR',
      'QR code downloaded successfully!',
      'QR code saved to gallery successfully!',
      'Permission to save image to gallery was denied',
      'Unable to access QR code image',
      'Failed to save QR code to gallery',
      'Upload Payment Proof (Receipt)',
      'Take a screenshot of your payment receipt after paying and upload it here.',
      'Receipt attached successfully',
      'Change Screenshot',
      'Select Payment Proof Screenshot',
      'Tap to choose screenshot from Gallery',
      'Submit Payment Proof',
      'Payment proof selected! Tap submit to proceed.',
      'Please upload your payment proof screenshot',
      'Invalid payment proof: This image does not appear to be a genuine payment receipt. Please upload a clear screenshot of your successful UPI transaction.',
      'Invalid image: No transaction or receipt text found. Please upload a clear screenshot of your payment receipt.',
      'Failed to verify payment proof image. Please ensure the screenshot is clear and try again.',
      'Payment proof submitted successfully. Please wait for owner confirmation.',
      'Approve & Credit Coins',
      'Select Coins Package to Credit:',
      'Or Custom Coins Amount:',
      'Enter custom coins...',
      'Remarks for User (Sent via System Notification):',
      'Enter remarks for user notification...',
      'Approve & Add Coins',
      'Please select or enter coins to credit',
      'Recharge approved! Added',
      'Payment receipt attached',
      'Tap to view full receipt',
      'Payment verified & coins added',
      'Receipt verified successfully',
      'Bonus coins added',
      'Payment approved by owner',
      'Payment approved & coins added',
      'Payment verified & coins credited successfully',
      'Auto-clears after 5 minutes',
      'Coins added to your wallet',
      'Official Payment UPI ID',
      'Copy UPI ID above or tap payment app below',
      'Complete payment and enter 12-digit UTR below',
      'Pay via UPI App (Copies UPI & Launches App):',
      'Other UPI',
      'Could not launch UPI app. UPI ID copied to clipboard: ',
      'Common Functions',
      'Income',
      'Task',
      'Couple',
      'Family',
      'YoYo judge review',
      'Games',
      'Space Voyage',
      'Premium Slots',
      'Zoo Slots',
      'Super Slots',
      'Crazy Lion',
      'Bingo Slots',
      "Bull's Reign",
      'Greedy Baby',
      'Wheel36',
      'Fun Dice',
      'Color Fun',
      '3Patti',
      'Lucky 77',
      'Lucky YoYo',
      'Lion Tiger Contest',
      'Verification Center',
      'Store',
      'Badge',
      'Title',
      'Tools',
      'Level',
      'Coupon',
      'Help',
      'Setting',
      'Come to join the family!',
      'Join Now',
      'Moment',
      'Personal Signature',
      'Contributed',
      'Top Supporters',
      'The Wish',
      'No CP Relationship yet',
      'Send a CP card in room to form a couple',
      'Ranking',
      'Basic Information',
      'Click to Change Avatar',
      'Cover Photo',
      'Nickname',
      'Birthday',
      'Bio',
      'Gender',
      'Boy',
      'Girl',
      'Height',
      'Weight',
      'Occupation',
      'Country or Region',
      'Change Avatar',
      'Choose from Gallery',
      'Enter Image URL',
      'Change Cover Photo',
      'Select Gender',
      'Set Birthday',
      'Edit Bio',
      'Enter Height',
      'Enter Weight',
      'Enter Occupation',
      'Select Country',
      'No countries found',
      'Profile updated successfully',
      'Confirm',
      'Tell something about yourself',
      'Enter nick name',
      'Edit Profile',
      'Members',
      'On Seat',
      'Participants',
      'No users on seat',
      'No other participants',
      'Users who take a seat will appear here',
      'Users listening in the room will appear here',
      'Audience',
      'Live',
      'Muted',
      'Search rooms, stars, or friends...',
      'All',
      'User',
      'Room',
      'Family',
      'Follow',
      'Following',
      'Join',
      'No results found',
      'No users found',
      'No rooms found',
      'No families found',
      'Family feature coming soon!',
      'Followed successfully',
      'Unfollowed successfully',
      'Try searching for a different user, room name, or ID',
      'Try searching by user name or ID',
      'Room Settings',
      'Host Team',
      'Admin Team',
      'Room Members',
      'Kicked-out Users',
      'My People',
      'Admin rights',
      'Host rights are granted only when host seat is occupied. User can be host and admin at the same time.',
      'Authority',
      'Host',
      'Admin',
      'Room owner',
      'Seat Lock',
      'Invite on seat',
      'Accept/Reject seat application',
      'Kick off the seat',
      'Open Mic/Close Mic',
      'Forbid from sending images in the room',
      'Kick off the room',
      'Set/Cancel Admin',
      'Set/Cancel Host',
      'Accept/Reject member application',
      'Play music',
      'Play sound effect',
      'Start/End the counter',
      'Remove Host',
      'Remove Admin',
      'Are you sure you want to remove',
      'from Host team?',
      'from Admin team?',
      'Removed from Host team',
      'Removed from Admin team',
      'Failed to remove host',
      'Failed to remove admin',
      'No hosts in this room yet',
      'No admins appointed yet',
      'No members',
      'Room Tools',
      'Boss Seat',
      'Background',
      'Lucky Number',
      'Allow audience to send Lucky Number in the room',
      'Free Mode',
      'Allow audience to take seats freely',
      'Room Lock',
      'Enter the room with password',
      'Set Room Password',
      'Enter Room Password',
      'You have entered wrong password',
      'Room password set and locked successfully',
      'Room unlocked successfully',
      'Password verified! Welcome to room 🎉',
      'Okay',
      'Cancel',
      'Seat Settings',
      'Regular Seat',
      'Special Seat',
      '10 Seats',
      '12 Seats',
      '14 Seats',
      '17 Seats',
      '22 Seats',
      '27 Seats',
      '(1+8+1)',
      '(Room Level ≥ 20)',
      '(Room Level ≥ 25)',
      '(Room Level ≥ 30)',
      '(VIP Level ≥ 6)',
      'Music',
      'Birthday',
      'Royal',
      'Magic',
      'Dating',
      'Relationship',
      'Wedding',
      'Seat layout applied successfully! 🎉',
      'Seat layout reset to default',
      'Reset to Default',
      'Restore Default',
      'Default Mode',
      'Default (8 Seats)',
      'Requires Room Level',
      'Requires VIP Level',
      'Only Room Owner or Admin can change seat layout',
      'Applicants',
      'On Seat',
      'Participants',
      'Selected Seat',
      'Target Seat',
      'Agree',
      'Reject',
      'Members',
      'Invite',
      'Broadcast',
      'Hi friends! Let\'s go to my room to have fun!',
      'The broadcast will show in all rooms. All the users can enter the room by clicking on it.',
      'Offensive content is strictly not allowed. Any violator will be banned forever.',
      'Broadcast sent successfully to all rooms!',
      'Broadcast message cannot be empty',
      'Insufficient coins to send broadcast',
      'Insufficient coins! You need 1500 coins to send a broadcast.',
      'Insufficient coins! You need 750 coins to send a broadcast.',
      'Join Room',
      'Enter Room',
      'Live Broadcast',
      'You are already in this room!',
      'Leaving current room & entering broadcast room...',
      'Gather Members',
      'Star Calculator',
      'Combat',
      'Room PK',
      'Game PK',
      'My music',
      'Play local music',
      'Play music in other apps',
      'After it is turned on, when you play music in other apps or when other app starts playing audio, users in the room can also hear it.',
      'Add music',
      'Confirm Adding',
      'Edit',
      'Save',
      'Delete',
      'Pick from device',
      'Pick audio from device storage',
      'No music added yet',
      'Tap Add music below to add songs from your device',
      'No audio files selected yet',
      'Select songs from phone (Audio tab)',
      'Tap Audio tab in phone to select all music without searching folders',
      'Select Audio',
      'Select Music from Phone',
      'Select audio files from phone',
      'Pick All / Multiple Songs',
      'Music added successfully',
      'Selected music deleted',
      'Please select at least one song to add',
      'Please select at least one song to delete',
      'Sound Effect',
      'Tap a sound to play it',
      'Cheer',
      'Clap',
      'Win',
      'Awkward',
      'Laugh',
      'Mock',
      'Horror',
      'Wow',
      'Cry',
      'Love',
      'Lucky Draw',
      'Soccer Rival',
      'Task',
      'Lucky Packet',
      'Lucky number',
      'entered the room',
      'No gift effects',
      'No enter effects',
      'Mute',
      'Classic',
      'VIP',
      'CP',
      'Games',
      'Match Draw! Bets Refunded 🤝',
      'Match ended in a Draw! Bets refunded.',
      'MATCH DRAW! 🤝',
      'All bets refunded.',
      'Reason for Rejection:',
      'Reject Recharge Request',
      'Enter rejection reason...',
      'Please enter a rejection reason',
      'Payment not received',
      'Incorrect amount transferred',
      'UTR / Reference mismatch',
      'Fake transaction proof',
      'Confirm Rejection',
      'Recharge request rejected successfully',
      'Pay via UPI App',
      'OR SCAN QR CODE',
      '12-Digit UTR / UPI Ref Number',
      'Mandatory: Found on your UPI payment receipt after paying',
      'Enter 12-digit UTR (e.g. 429182746192)',
      'Please enter valid 12-digit UTR / UPI Reference Number from payment receipt',
      'This UTR number has already been used for another recharge request.',
      'No UPI app found on your phone. Please scan the QR code to pay.',
      'Could not launch UPI app. Please scan the QR code to pay.',
      'UTR No.',
      'Search by user name, ID, UTR, or payment mode...',
      'Lion',
      'Wolf',
      'Panda',
      'Unicorn',
      'Dragon',
      'Hairy Creature',
      'needed to reach',
      'Progress',
      'Next',
      'MAX LEVEL',
      'Test Level Up (Instant Real-time Sync)',
      'Level and EXP reset to Level 1',
      'Reset failed. Please try again.',
      'Maximum Level Reached! You have attained ultimate prestige!',
      'Congratulations!',
      'Leveled up to Level',
      'Novice',
      'Knight',
      'Master',
      'Royale',
      'Legend',
      'Divine',
      'Active Frame',
      'Dancer',
      'Phoenix',
      'Cat',
      'Smiling Cat',
      'Joy Cat',
      'Heart Eyes Cat',
      'Smirk Cat',
      'Kissing Cat',
      'Scream Cat',
      'Crying Cat',
      'Pouting Cat',
      'Couple Kiss',
      'Warm Hug',
      'Proposal',
      'Couple Dance',
      'Holding Hands',
      'Love Lock',
      'Wedding',
      'Shy Love',
      'Love Hug',
      'Sweet Cuddle',
      'Romantic Kiss',
      'Heart Pop',
      'Pure Warmth',
      'Gentle Care',
      'Seals',
      'Seal Pleading',
      'Seal UwU',
      'Seal Hearts',
      'Seal Cheer',
      'Happy Dance',
      'Wiggle Dance',
      'Birthday Drum',
      'Squishy Seal',
      'Seal Crying',
      'Sad Roll',
      'Seal Tired',
      'This Is Fine',
      'Looking Around',
      'Finger Gun',
      'Surrender',
      'Bang Bang',
      'Sign in with Google / Gmail',
      'Instant 6-Digit Email OTP',
      'Sign in with Phone Number',
      'Fast SMS Verification Code',
      'Mobile Phone Login',
      'Gmail / Email Login',
      'Mobile Number',
      'Enter 10-digit number',
      'Get OTP',
      'Resend',
      'Enter 6-Digit SMS OTP',
      'Enter 6-Digit Email OTP',
      'Enter 6-digit OTP',
      'Verify OTP',
      'Verified ✅',
      'Your Full Name',
      'Verify & Login',
      'Verify OTP First to Login 🔒',
      'Gmail / Email Address',
      'By continuing, you agree to our',
      'Terms of Service',
      'Privacy Policy',
      'and',
      'Choose Language',
      'Search language...',
      'Please enter a valid 10-digit mobile number',
      'Message Sent Successfully',
      'Failed to send OTP',
      'Please enter the 6-digit OTP code',
      'OTP Verified Successfully! ✅',
      'Wrong OTP! Please enter correct 6 digit OTP',
      'Please verify your OTP first',
      'Please enter your full name',
      'Login Successful! Welcome 🎉',
      'Login failed',
      'Please enter a valid Gmail / Email address',
      'YoYo Rooms',
      '🟢 Live Voice Chat',
      'Logout',
      'Do you want to logout from your account?',
      'Cancel',
      'Create Room',
      'Register New Account',
      'Gmail Account Login',
      'Login User',
      'Register User',
      'Enter Gmail ID',
      'OTP code sent to your Gmail inbox!',
      'Failed to send OTP to email',
      'Failed to send Email OTP',
      'Create Password',
      'Confirm Password',
      'Passwords Match',
      'Mismatch',
      'Register & Create Account',
      'Already have an account?',
      'New to YoYo?',
      'Password Verified Successfully! Welcome 🎉',
      'Registration Successful! Welcome 🎉',
      'Registration failed',
      'Invalid email or password',
      'Password must be at least 4 characters long',
      'Password and Confirm Password do not match!',
      'Please enter your password',
      'Tap "Get OTP" first',
      'Verify OTP First',
      'Fill All Required Fields',
      'Check your Gmail Inbox & Spam folder',
      'Mobile Number Login',
      'Account not found with this Mobile Number! Please click Register User first.',
      'Please verify your Mobile OTP first before completing registration',
      'SMS OTP code sent to your mobile!',
      'Waiting for OTP...',
      'Re-enter your password',
      'At least 4 characters',
      'e.g. Rahul Sharma',
      'Related',
      'Party',
      'Activity',
      'Recently',
      'Following',
      'People you may like',
      'Follow',
      'Following',
      'Mine',
      'Room',
      'Gaming',
      'Discover',
      'Message',
      'Me',
      'Create Your Room',
      'Daily Check-in',
      'Check-in Successful! +100 Coins Claimed 🎉',
      'Virtual Lover',
      'YoYo Star',
      'YoYo Fan',
      'Your Online Soulmate',
      'Ludo',
      'Dominos',
      'UNO',
      'Games',
      'BETS',
      '1 ON 1',
      '4 Players',
      '2 Players (1 ON 1)',
      'Play Now',
      'Marvel Ludo',
      'Snake&Ladder',
      'Ludo Coin',
      '5/Point',
      '200 Limits/Round',
      'Get',
      'Claimed',
      'Daily Game Coins',
      'Claim free coins daily! Streak increases your reward.',
      'Game Bet',
      'Your Balance',
      'Game Coins',
      'Select Play Mode',
      'Online Battle',
      'Match with online players',
      'Local Play',
      'Pass & Play / vs AI',
      'Number of Players',
      'Insufficient Game Coins! Please claim free coins from the Silver Chest.',
      'Open Silver Chest 🎁',
      'Find Match & Play 🎮',
      'Play Online 🎮',
      'Play Online',
      'Start Local Game 🎮',
      'Exit Game',
      'Your Turn to Roll!',
      'Opponent is Rolling...',
      'Tap dice to roll!',
      'Waiting for opponent',
      'VICTORY! 🏆 +180 Coins',
      'MATCH OVER',
      'Done',
      'Your Cards (Tap to Play)',
      'Draw',
      'UNO! Only 1 card left! 🔥',
      'Dominoes Board',
      'Your Tiles (Tap matching tile)',
      'Featured Games',
      'Aap aaj ka Silver Chest pehle hi claim kar chuke hain! Kal dobara milega.',
      'Aap aaj ka Silver Chest pehle hi claim kar chuke hain! Ek din me sirf ek bar hi get kar sakte hain. Kal dobara aaiye ya previous games jeet kar coins badhaiye.',
      'Aap aaj ka Silver Chest reward pehle hi claim kar chuke hain! Kal dobara aaiye.',
      'View Streak Info ℹ️',
      'Victory!',
      'You won',
      'Game Coins!',
      'VICTORY! 🏆',
      'Coins',
      'Main Wallet Coins:',
      '(Use Game Coins to play games)',
      'Game Store coming soon! 🏪',
      'Coming Soon',
      'VIP Emojis',
      'CP Emojis',
      'Games Emojis',
      'GAMES Emojis',
      'Opponent reached home! Better luck next time.',
      'Opponent finished their cards! Better luck next time.',
      'Drew a card from deck!',
      'Tile placed! Opponent thinking...',
      'Opponent placed a tile! Your turn.',
      'Tile dots must match the open end!',
      'Card must match color or number!',
      'Already Claimed for Today! Come back tomorrow',
      'Already Claimed for Today! Next claim available tomorrow',
      'Day 1',
      'Day 2',
      'Day 3',
      'Day 4',
      'Day 5',
      'Day 6',
      'Day 7',
      'Daily Reward Unlocked!',
      'Silver Chest Unlocked!',
      'Awesome! Close',
      'Collect & Close',
      'Coins added to your Game Balance',
      'Play Ludo, Dominos & UNO to win more!',
      'Day 1 Claimed!',
      'Day 2 Claimed!',
      'Day 3 Claimed!',
      'Day 4 Claimed!',
      'Day 5 Claimed!',
      'Day 6 Claimed!',
      'Day 7 Claimed!',
      'Quit Game?',
      'If you leave the match now, your bet coins will be forfeited!',
      'Carrom Board',
      'Pieces',
      'White',
      'Black',
      'Aiming...',
      'Your Turn - Aim & Strike!',
      'Opponent Turn',
      'Bets / Player',
      'Winner Takes Pot',
      'Deducted',
      'Baseline',
      'STRIKE',
      'Striker Foul! Turn Passed! ⚠️',
      'Victory! You Won the Carrom Match! 🏆',
      'Match Lost! Opponent cleared the board.',
      'Great Shot! Extra Turn! 🎯',
      'AI Aiming... 🎯',
      'Power',
      'Tap coin to auto-aim',
      'Nudge',
      'Pocket Aligned! 🎯',
      'Target Locked! 🎯',
      'TARGET LOCKED',
      'Opponent scored! Extra Turn! 🎯',
      'Opponent pocketed a coin! Extra Turn! 🎯',
      'Team A',
      'Team B',
      'Team A (P1 & P3)',
      'Team B (P2 & P4)',
      'Pts',
      'Bottom',
      'Left',
      'Top',
      'Right',
      '4 Player Battle',
      'Keep Playing',
      'Quit Game',
      'Match forfeited!',
      'Match lost!',
      'Game Coins deducted.',
      'Insufficient Game Coins!',
      'Insufficient Game Coins! Please claim free coins from the Silver Chest.',
      'Insufficient Game Coins! 100 coins required to join this match.',
      'Insufficient Game Coins! 100 coins required to create this match.',
      'DEFEAT 😢',
      'QUIT / FORFEITED ⚠️',
      'Ludo Classic',
      'Roll Dice',
      'Your Turn!',
      "Opponent's Turn",
      'Rolled a 6! Roll Again 🎲',
      'PK! Opponent token cut! ⚔️',
      'Token reached HOME! 🌟',
      'Tap glowing token to move',
      'No valid moves',
      'Tokens Home',
      'You',
      'Opponent',
      'Opponent (AI)',
      'Green',
      'Yellow',
      'Blue',
      'Bonus Turn!',
      "Opponent's Turn — Rolling...",
      'Opponent rolled',
      'Opponent rolled a 6! Unlocking goti 🚀',
      'Advancing goti...',
      'Your Turn! Roll Dice 🎲',
      'Rolling...',
      'AI Playing',
      'Match Lobby',
      'BETS',
      'Bets',
      'Bets : Coins',
      'Select Bet Amount',
      'Choose match stakes in Game Coins',
      'Bet set to',
      'Coins',
      'Match Bet Set by Host',
      'Match Bet',
      'Game Bet',
      'Tap to join room',
      'You have sufficient coins to join this match.',
      'Insufficient Coins to Join ⚠️',
      'All players must have at least the selected bet amount to join the match.',
      'POT',
      'Total Pot',
      'VICTORY! 🏆',
      'DEFEAT 😢',
      'Game Coins deducted.',
      'Winner Pot',
      'Winner Takes Pot',
      'Bets / Player',
      'Bet Per Player',
      'Deducted Upfront',
      'Deducted on entry',
      'All player bets pooled into center pot',
      'Match Stake & Pot Pool',
      'Host left the game room. Bet coins refunded.',
      'Waiting for Player 2 to join... ⏳',
      'Waiting for at least 2 players... ⏳',
      'Minimum 2 players required to start match',
      'Start Match Now 🚀',
      'Players Ready',
      'Add Player',
      'Host',
      'Player',
      'Room Code',
      'Player Mode',
      'Cancel Lobby',
      'Join Match with Room Code',
      'Live Waiting Rooms',
      'Join',
      'Waiting',
      'Enter Room Code',
      'Enter the 4-digit code shared by the host to join their game room:',
      'Enter 4-digit code (e.g. 1234)',
      'Join Match 🎮',
      'Please enter a valid 4-digit Room Code!',
      'Connecting to game server...',
      'Joined lobby successfully!',
      'Minimum 2 registered players required to start match!',
      'Share Room Code',
      'with another registered player to join!',
      'Game room not found or match already started.',
      'Game room is already full!',
      'Empty Slot',
      'Tap + to Join',
      'Select Player',
      'Select an active registered user to join this match:',
      'No other registered players available!',
      'All other registered players are already in this match.',
      'Registered User ✅',
      'Player removed from slot',
      'This player is already in this match!',
      'joined the match!',
      'You are already in this room! Waiting for another player to join...',
      'Waiting for another registered player to join...',
      'Join Game with Game Code',
      'Join Game',
      'Enter Game Code',
      'Enter the 4-digit Game Code shared by Player 1:',
      'Enter 4-digit Game Code',
      'Join Lobby 🚀',
      'Please enter a valid Game Code!',
      'Game Code verified! Click + on Slot 2 to join.',
      'You are already joined in this room! Share Game Code with another player.',
      'You already created or joined this lobby! Same user cannot join twice.',
      'Game Code',
      'Lobby Activity & Connected Players',
      'Created this room',
      'Joined via Game Code',
      'In Lobby',
      'entered the lobby waiting room!',
      'is in this lobby! Waiting to tap +',
      'Waiting for Player 2! Share Game Code #',
      ' with them to join.',
      'Joined match lobby successfully! Ready to play.',
      'Waiting for Host to start match...',
      'Only the lobby host can start the match!',
      'Opponent left the match! You won',
      'left the match. Game continues for the remaining pot!',
      'You left the match! Bet coins forfeited.',
      'Left Match',
      'Forfeited',
      'Left',
      'Snakes & Ladders',
      'Snake & Ladder',
      'Position',
      'Need exact roll to reach 100!',
      'Rolled a 6! Extra Turn!',
      'Super Climb! Climbed from',
      'Snake Bite! Dropped from',
      'Exit Snake & Ladder Match?',
      'If you exit now, you will forfeit this match and the total pot will be awarded to your opponent.',
      'Forfeit & Exit',
      'VICTORY! You reached 100!',
      'DEFEAT! Opponent reached 100!',
      'climbed ladder to',
      'bitten by snake down to',
      'WIN',
      'Tic Tac Toe',
      'Zero Kata',
      'Playing as',
      'Thinking...',
      'Match Draw! Bets Refunded 🤝',
      'Match ended in a Draw! Bets refunded.',
      'VICTORY! You won the match!',
      'DEFEAT! Opponent won the match!',
      '1 ON 1 Classic',
      '1 ON 1 Turbo',
      'Mode Mismatch!',
      'Host created a',
      'match.',
      'Turbo ⚡',
      'Classic 👑',
      'Wrong Mode: Open ',
      'mode!',
      'Checking Room... ⏳',
      'Carrom',
      'Carrom Board',
      'Authentic Disc Battle • Winner Takes Pot',
      'Victory! You Won the Carrom Match! 🏆',
      'Congratulations! You won the Carrom Match! 🏆',
      'Match Lost! Opponent cleared the board.',
      'Striker Foul! Turn Passed! ⚠️',
      'Great Shot! Extra Turn! 🎯',
      'AI Aiming... 🎯',
      'Baseline',
      'Angle',
      'Soft',
      'Med',
      'Max',
      'STRIKE!',
      'Pieces',
      'Carrom Board Battle',
      'Board',
      'Striker',
      'Dice Battle',
      'High Roller Duel • Best of 3 Rounds • Winner Takes Pot',
      'ROLL DICE',
      'Rolling...',
      'Wait for Turn',
      'Wait for your turn!',
      'You won this Round!',
      'Opponent won this Round!',
      'Round Tied! Re-rolling...',
      'You won with higher roll',
      'won with higher roll',
      'You conquered the Dice Battle!',
      'Opponent rolled higher this match!',
      'Turbo Blitz',
      'Best of 3',
      'Your Wins',
      'Total Pts',
      'ROUND',
      'TIMER',
      '👆 TAP DICE TO ROLL',
      'Card Clash',
      'High Card Clash',
      'High Card Duel • Ace is High • Winner Takes Pot',
      'DRAW CARD',
      'Drawing Card...',
      '👆 TAP TO DRAW',
      'Round Tied! Re-drawing...',
      'Cards Tied! Re-drawing...',
      'You won with higher card',
      'won with higher card',
      'You conquered the Card Clash!',
      'Opponent drew higher cards this match!',
      'Rounds',
      // Time Bomb Pass
      'Time Bomb Pass',
      'Pass the bomb before it blows! Last survivor wins the pot.',
      'Game started! Pass the bomb fast!',
      'Bomb passed!',
      'Next round! Keep passing!',
      'got blown up!',
      'You survived!',
      'survived the bomb!',
      'PASS THE BOMB!',
      'Quick! Pass it before it explodes!',
      'Waiting for',
      'Pray they pass it your way!',
      'START GAME',
      'coin pot',
      'YOU SURVIVED!',
      'The bomb never got you!',
      'BOOM!',
      'survived!',
      'Play Again',
      'Alive',
      '1 ON 1 Duel',
      '3 Player Bomb',
      '4 Player Chaos',
      'Time Bomb Pass',
      'Write a comment...',
      'Say hi',
      'Say something nice...',
      'Send Photo',
      'Permission to access photos is required!',
      'Photo sent to room!',
      'Failed to send photo',
      'Sexual and violent contents are not allowed. All violators will be banned from the chatroom. Please respect each other and do not expose your personal info.',
      'Emojis',
      'Send Photo to Room',
      'Add a caption... (optional)',
      'Crop / Edit',
      'Change Photo',
      'Failed to open photo picker',
      'Send',
      'You are already on the Host seat! Step down from hosting first.',
      'You are currently on the Host seat. Please step down from Host seat first.',
      'Only the room owner can take the Host seat.',
      'Take Host Seat 👑',
      'You took the Host seat 👑',
      'You stepped down from the Host seat 👑',
      'You left the mic seat 🪑',
      'Seat already occupied',
      'Change Seat',
      'Do you want to switch to this seat?',
      'Switch',
      'Leave Hosting',
      'Take Host',
      'Please take a mic seat first to speak',
      'Microphone Muted',
      'Microphone Unmuted',
      'Unblock',
      'Valid till forever',
      'Valid till 3 days',
      'Kicked out by',
      'User unblocked successfully',
      'Failed to unblock user',
      'No kicked-out users',
      'Search by user name or ID',
      'No users found matching your search',
      'No users are currently kicked from this room',
      'User cannot enter this room until you unblock them from Kicked-out Users.',
      'User cannot enter this room for 3 days or until unblocked.',
      'User kicked successfully',
      'User kicked from room for 3 days.',
      'User kicked from room permanently until unblocked.',
      'You have been kicked out of this room. You cannot enter until you are unblocked.',
      'You have been kicked out of this room.',
      'Only room owner or admin can kick users',
      'Only room owner or admin can unblock users',
      'Failed to load kicked users',
      '1 month',
      '3 months',
      '12 months',
      'Not Activated Yet',
      'Activated',
      'days left',
      'Buy',
      '1. After payment, the host seat will be upgraded to the Boss Seat',
      '1. After payment, the Boss Seat will be displayed next to the host',
      '2. The owner, host, and admin can invite users in the chat room to join the Boss Seat',
      '3. After expiration, it will automatically removed',
      'Not enough coins, please recharge first',
      'Boss Seat activated successfully!',
      'Failed to purchase Boss Seat',
      'Take Boss Seat 🛋️',
      'Do you want to sit on the Boss Seat?',
      'You took the Boss Seat 🛋️',
      'You stepped down from the Boss Seat 🛋️',
      'Take Boss Seat',
      'Leave Boss Seat',
      'Tap to Host (Boss)',
      'User removed from Boss Seat',
      'Boss',
      'Applicants',
      'On Seat',
      'Participants',
      'Members',
      'Invite',
      'Agree',
      'Reject',
      'Apply for Seat 🪑',
      'Free Mode is OFF. Do you want to apply for this seat?',
      'Apply',
      'Application sent to host! 📨',
      'Applicant placed on seat! 🎉',
      'Application declined',
      'Free Mode Enabled (Anyone can take seats)',
      'Free Mode Disabled (Application required)',
      'No other audience in room',
      'Users listening in the room will appear here',
      'No seat applicants yet',
      'When users apply for a seat, they will appear here',
      'Choose to PK mode',
      'Match',
      'Invite a room',
      'Search Room',
      'Invite',
      'Invited',
      'PK Battle Challenge!',
      'Challenged your room to a PK Battle!',
      'has challenged your room to a PK Battle!',
      'Accept',
      'Reject',
      'PK battle rejected',
      'Searching for rival room...',
      'Match found! Starting PK battle...',
      'PK Battle Started!',
      'PK Battle Ended',
      'Victory!',
      'Defeat',
      'Draw',
      'Battle forfeited! Rival room turned off Room PK.',
      'You forfeited the battle by turning off Room PK.',
      'Target room is already in a PK battle',
      'Cancel Matchmaking',
      'Finding match...',
      'VS',
      'Cancel',
      'OK',
      'Points',
      'Winner',
      'Loser',
      'No other active rooms online right now. Waiting for rival room to match...',
      'No other active rooms online right now.',
      'Target room is currently inactive or empty.',
      'No active rooms online',
      'Common',
      'Password',
      'Countdown',
      'Number',
      'Coins',
      '(20≤Numbers≤100)',
      '(≥ 300 Coins)',
      'Enter password',
      'Rules',
      'Send',
      'Get',
      'Opened',
      'Lucky Packet sent successfully!',
      'Failed to send lucky packet',
      'Failed to open lucky packet',
      'Insufficient gold coins to send this lucky packet',
      'Please enter a password between 4 and 20 characters',
      'For each Packet, the number of recipients must be greater than or equal to 20',
      'Lucky package can be put in gold coins. When putting in coins, a minimum of 300 coins must be put in',
      'When putting in coins, a minimum of 300 coins must be put in',
      'When a Packet pack is more than 3000 coins, a chatroom broadcast will be sent',
      'Lucky package will open in 5 minutes',
      'I sent a Lucky Packet',
      'Enter the correct password to loot this lucky packet',
      'Wrong password. You cannot loot this lucky packet.',
      'You have already opened this lucky packet',
      'This lucky packet is empty',
      'Better luck next time',
      'You did not receive gold coins this time',
      'Please enter the password',
      'Come to join the family!',
      'Join Now',
      'Title',
      'Add',
      'CP Relationship',
      'Basic Information',
      'Personal Signature',
      'Gender',
      'birthday',
      'Country or Region',
      'Top Supporters',
      'The Wish',
      'No CP Relationship yet',
      'Send a CP card in room to form a couple',
      'Tell something about yourself',
      'No signature set yet',
      'Enter nick name',
      'Save',
      'Ranking',
      'Contributed',
      'Received',
      'Visitors',
      'View & Edit Profile',
      'Edit Profile',
      'Photo URL',
      'Cover Image URL',
      'Profile updated successfully',
      'Add Game feature coming soon',
      'Wallet',
      'Coins',
      'Diamonds',
      'Game Coins',
      'Refresh to check coin balance',
      'Balance refreshed successfully',
      'Help Center',
      'How to use Diamonds',
      '1. You can buy gifts with Diamonds',
      '2. You can buy tools with Diamonds',
      'How to earn Diamond',
      'Finish Daily Tasks can earn Diamond',
      'Store',
      'Earn',
      'Custom Exchange',
      'Coins Balance:',
      'Number of Coins',
      'Exchange',
      'Description',
      'Exchange Rate: 1 Gold Coin = 10 Game Coins',
      'Insufficient gold coins balance',
      'Insufficient gold coins balance, please recharge first',
      'Please enter a valid coin amount',
      'Recharge package selected:',
      'Payment gateway integration coming soon',
      'Store coming soon',
      'Transaction history coming soon',
      'Recharge Methods',
      'Recharge amount:',
      'Scan QR code to pay using any UPI app',
      'Select Payment App',
      'Submit Payment Request',
      'Please wait for confirmation',
      'Your recharge request is pending approval. You cannot make another purchase until this order is confirmed.',
      'Payment approved successfully for amount',
      'Payment rejected for amount',
      'Upload your QR code to receive the refund amount',
      'Upload Refund QR',
      'QR Code Uploaded Successfully',
      'Confirm Money',
      'Search by user name, ID, or payment mode...',
      'All',
      'Pending',
      'Approved',
      'Rejected',
      'Approve',
      'Reject',
      'User',
      'ID',
      'Mode',
      'Amount',
      'Action',
      'Tap to enlarge',
      'Waiting for refund QR',
      'Refund QR Code',
      'Close',
      'Recharge request submitted successfully. Please wait for confirmation.',
      'Recharge request approved successfully',
      'Recharge request rejected',
      'Payment Proof',
      'Upload Payment Proof',
      'Proof Submitted',
      'Proof Under Review',
      'Payment Proof Submitted',
      'View Proof',
      'Payment Proof Verification',
      'Review Proof',
      'New payment proof submitted by user!',
      'Did you pay successfully? Upload payment receipt below for review',
      'Change Payment Proof',
      'Re-verify Payment',
      'Payment proof submitted successfully. Owner will review your receipt.',
      'Failed to upload payment proof',
      'No QR code detected in this image. Please upload a clear, valid payment QR code.',
      'Invalid payment proof: No payment or transaction details detected. Please upload a clear screenshot of your payment receipt.',
      'If you have any query about this rejection then upload payment proof or if you want a refund then upload your refund QR code',
      'Message',
      'Moment',
      'Notification',
      'System Notification',
      'Family',
      'No Messages Yet',
      'When you or other users send messages, they will appear here.',
      'No System Notifications',
      'System alerts and wallet recharge updates will appear here.',
      'Coins Recharge Rejected',
      'Payment Proof Under Review',
      'Recharge Approved',
      'Tap to submit payment proof or refund QR',
      'Recharge Rejection Dispute',
      'Choose a resolution option',
      'Upload Payment Proof (Receipt)',
      'If you already paid, upload clear screenshot with UTR number for AI re-verification.',
      'Upload Refund QR Code',
      'Upload your PhonePe/GPay QR code to receive your refund directly to your bank.',
      'Upload Proof',
      'Upload QR',
      'Recharge updates pending',
      'System messages & wallet alerts',
      'Clan & family announcements',
      'No new family notifications',
      'Moments coming soon! ✨',
      'Payment proof verified and submitted to owner successfully!',
      'Refund QR code uploaded successfully! Owner will process refund.',
      'Proof submitted. Awaiting owner review.',
      'Resolved',
      'Resolve',
      'Query / Dispute Resolved',
      'Issue Resolved by Owner',
      'Tap to acknowledge and clear from notifications',
      'Got it',
      'Query resolution acknowledged',
      'Resolve Recharge Dispute',
      'Quick Select Resolution Message:',
      'Enter Resolution Message for User:',
      'Submit Resolution',
      'Refund processed to your QR code successfully.',
      'Payment verified! Coins credited to your wallet.',
      'Payment proof verified. Issue resolved.',
      'Dispute resolved. Thank you for your cooperation.',
      'Auto-clears after 5 minutes',
      'Please upload your payment proof screenshot or QR code',
      'Valid payment QR code / receipt attached successfully!',
      'Verifying QR code / payment proof...',
      'Checking for valid payment QR matrix or transaction receipt',
      'Choose Upload Option',
      'Only valid QR codes or payment receipts are accepted. Random photos cannot be uploaded.',
      'Select QR Code / Receipt from Gallery',
      'Choose downloaded QR or payment receipt from phone',
      'Scan QR Code with Camera',
      'Snap a photo of the QR code or payment screen',
      'Upload QR code or payment transaction screenshot',
      'Invalid image! Only valid payment QR code or transaction screenshot is accepted. Random photos are not allowed.',
      'Invalid image: Only QR code or payment receipt allowed.',
      'Permission to access camera is required',
      'Save or Share QR Code',
      'Select Save Image to save QR code to your phone',
      'Payment proof submitted successfully! Check System Notifications for status.',
      'Recharge Request Pending',
      'Your payment proof is pending owner verification.',
      'If you have any query, click here',
      'User Problems',
      'Active Problems',
      'No User Problems Found',
      'When users submit a query for rejected recharges, they will appear here.',
      'Swipe horizontally to view full dispute details',
      'User Query / Reason',
      'Rejection Note',
      'Resolve User Dispute',
      'Dispute Payment Proof',
      'Resolve Dispute',
      'Credit Coins to User Wallet?',
      'Turn on if the user payment was verified and genuine',
      'Coins to credit:',
      'Enter coins...',
      'Submit Resolution',
      'Submit Your Query',
      'Explain your problem or query',
      'Explain why your payment was valid or details of the deduction...',
      'Upload Payment Proof (Receipt / QR Screenshot)',
      'Choose Payment Screenshot',
      'Change Screenshot',
      'Submit Query',
      'Please enter your query or reason',
      'Please select a payment proof screenshot',
      'Your query and payment proof have been submitted to owner for review.',
      'Query submitted. Under owner review in User Problems.',
      'Dispute marked as resolved successfully',
      'Failed to resolve problem',
      'New user query submitted!',
      'Query Under Review',
      'Followers',
      'No Followers Yet',
      'When another user follows you, their activity will appear here.',
      'followed you, click here to follow them back and become new friends! 👏',
      'Followed back successfully!',
      'New follower!',
      '1 days ago',
      'Just now',
      'minutes ago',
      'hours ago',
      'days ago',
      'Trending',
      'No Following Posts Yet',
      'No Trending Posts Yet',
      'Follow users or explore trending feed to see new posts.',
      'Be the first to share a post, photo, or status with friends!',
      'Explore Trending',
      'Create Post',
      'New Post',
      'Comments',
      'Write a comment...',
      'No comments yet. Say something!',
      'Add Photo',
      'Public',
      'Post shared successfully! 🎉',
      'Followed user successfully!',
      'Unfollowed user',
      'Maximum 2 photos allowed per post',
      "What's on your mind? Share thoughts, poetry, or moments...",
      'Join the Family to unlock privileges',
      'Get double Crystals',
      'Get Gift Rewards',
      'Unlock exclusive family tools',
      'Unlock Family Tasks',
      'Family Recommendations',
      'No Families Created Yet',
      'Be the first captain to create your family and invite members!',
      'Joined',
      'Pending',
      'Create a Family',
      'Family Name',
      'Create a Name for your Family',
      'Family Tag',
      'Set a Tag for your Family',
      'Once the family tag is set, it cannot be changed!!!',
      'Family Announcement',
      'Write an Announcement for your Family',
      'Review method',
      'Pass automatically',
      'Users will automatically join the family after apply',
      "Admin's Review",
      'After the user applied, users can join the family after being confirmed by the family admin.',
      'Join Requirements',
      'no request',
      '1.Free create for above level 30',
      '2.If family members receive coin gifts, the captain can also get some coin rewards',
      "3. The Captain can receive 1%-5% of coin rebates from the Family members' gifts every month",
      'Create for free',
      'User level requirements',
      'Wealth level requirements',
      'Please enter Family Name',
      'Please enter Family Tag',
      'Family created successfully! 🎉',
      'Join request submitted! Awaiting family admin review.',
      'Joined family successfully! 🎉',
    ])
  );

  const pendingRequests = useRef(new Set());

  useEffect(() => {
    initLanguage();
  }, []);

  const initLanguage = async () => {
    try {
      const savedLang = await AsyncStorage.getItem('@app_language');
      const langToUse = savedLang || detectDeviceLanguage();
      setCurrentLanguage(langToUse);
      if (langToUse !== 'en') {
        fetchBatchTranslations(langToUse);
      }
    } catch (e) {
      setCurrentLanguage('en');
    }
  };

  /**
   * Translates all phrases in ONE single batch call to Backend (~0.2s)
   * 100% Dynamic: Zero hardcoded dictionaries on server or client!
   */
  const fetchBatchTranslations = async (langCode) => {
    if (langCode === 'en') {
      setLiveTranslations({});
      return;
    }

    try {
      const phrasesArray = Array.from(knownPhrases.current);
      const res = await api.post('/translations/batch', {
        texts: phrasesArray,
        targetLang: langCode,
      });

      if (res.data && res.data.success && res.data.translations) {
        setLiveTranslations(res.data.translations);
        Object.entries(res.data.translations).forEach(([k, v]) => {
          ramCache.set(`${langCode}:::${k}`, v);
        });
        setRefreshTrigger((v) => v + 1);
      }
    } catch (err) {
      console.warn('[LanguageContext] Batch translate error:', err);
    }
  };

  const setLanguage = (langCode) => {
    if (!LANGUAGES.some((l) => l.code === langCode)) return;
    try {
      // 1. Instant switch in UI
      setCurrentLanguage(langCode);
      setIsModalOpen(false);

      // 2. Remember choice (only 2 chars saved in AsyncStorage: e.g. 'hi')
      AsyncStorage.setItem('@app_language', langCode).catch(() => {});

      // 3. Fast batch translation request in parallel
      fetchBatchTranslations(langCode);
    } catch (e) {
      console.error('[LanguageContext] Error setting language:', e);
    }
  };

  /**
   * Universal translation function:
   * Translates ANY sentence dynamically.
   * Zero hardcoded dictionaries!
   */
  const t = (keyOrText, fallback = '') => {
    if (!keyOrText) return '';

    const textToTranslate = fallback || keyOrText;
    knownPhrases.current.add(textToTranslate);

    if (currentLanguage === 'en') {
      return textToTranslate;
    }

    // 1. Check live RAM batch translations
    if (liveTranslations && liveTranslations[textToTranslate] !== undefined) {
      return liveTranslations[textToTranslate];
    }
    if (liveTranslations && liveTranslations[keyOrText] !== undefined) {
      return liveTranslations[keyOrText];
    }

    // 2. Check RAM cache
    const cacheKey = `${currentLanguage}:::${textToTranslate}`;
    if (ramCache.has(cacheKey)) {
      return ramCache.get(cacheKey);
    }

    // 3. Dynamic single translation in background if not yet in batch
    if (!pendingRequests.current.has(cacheKey)) {
      pendingRequests.current.add(cacheKey);
      api
        .post('/translations/translate', {
          text: textToTranslate,
          targetLang: currentLanguage,
        })
        .then((res) => {
          pendingRequests.current.delete(cacheKey);
          if (res.data && res.data.success && res.data.translated) {
            ramCache.set(cacheKey, res.data.translated);
            setLiveTranslations((prev) => ({
              ...prev,
              [textToTranslate]: res.data.translated,
              [keyOrText]: res.data.translated,
            }));
          }
        })
        .catch(() => {
          pendingRequests.current.delete(cacheKey);
        });
    }

    return textToTranslate;
  };

  const activeLangObj =
    LANGUAGES.find((l) => l.code === currentLanguage) || LANGUAGES[0];

  const filteredLanguages = LANGUAGES.filter((lang) => {
    const q = searchQuery.toLowerCase().trim();
    if (!q) return true;
    return (
      lang.name.toLowerCase().includes(q) ||
      lang.nativeName.toLowerCase().includes(q)
    );
  });

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        t,
        languagesList: LANGUAGES,
        openLanguageModal: () => {
          setSearchQuery('');
          setIsModalOpen(true);
        },
        closeLanguageModal: () => setIsModalOpen(false),
        activeLanguageName: activeLangObj.nativeName,
        activeLanguagePillText: `${activeLangObj.flag} ${activeLangObj.nativeName} (${activeLangObj.name})`,
      }}
    >
      {children}

      {/* Global Interactive Language Selection Modal */}
      <Modal
        visible={isModalOpen}
        transparent={true}
        animationType="slide"
        onRequestClose={() => setIsModalOpen(false)}
      >
        <View style={styles.modalOverlay}>
          <TouchableOpacity
            style={styles.backdropTouch}
            activeOpacity={1}
            onPress={() => setIsModalOpen(false)}
          />

          <View style={styles.sheetContainer}>
            {/* Sheet Handle */}
            <View style={styles.handleBar} />

            {/* Header */}
            <View style={styles.sheetHeader}>
              <View>
                <Text style={styles.sheetTitle}>🌐 {t('Choose Language')}</Text>
                <Text style={styles.sheetSubtitle}>
                  Current: {activeLangObj.flag} {activeLangObj.nativeName} ({activeLangObj.name})
                </Text>
              </View>
              <TouchableOpacity
                onPress={() => setIsModalOpen(false)}
                style={styles.closeBtn}
                activeOpacity={0.7}
              >
                <Text style={styles.closeBtnText}>✕</Text>
              </TouchableOpacity>
            </View>

            {/* Search Input */}
            <View style={styles.searchBox}>
              <Text style={styles.searchIcon}>🔍</Text>
              <TextInput
                style={styles.searchInput}
                placeholder={t('Search language...')}
                placeholderTextColor="#9CA3AF"
                value={searchQuery}
                onChangeText={setSearchQuery}
                autoCorrect={false}
              />
              {searchQuery.length > 0 && (
                <TouchableOpacity onPress={() => setSearchQuery('')}>
                  <Text style={styles.clearSearch}>✕</Text>
                </TouchableOpacity>
              )}
            </View>

            {/* Language Grid / List */}
            <FlatList
              data={filteredLanguages}
              keyExtractor={(item) => item.code}
              contentContainerStyle={styles.listContent}
              showsVerticalScrollIndicator={false}
              renderItem={({ item }) => {
                const isSelected = item.code === currentLanguage;
                return (
                  <TouchableOpacity
                    style={[styles.langItem, isSelected && styles.langItemSelected]}
                    activeOpacity={0.75}
                    onPress={() => {
                      setLanguage(item.code);
                    }}
                  >
                    <View style={styles.langLeft}>
                      <Text style={styles.flagIcon}>{item.flag}</Text>
                      <View>
                        <Text style={[styles.nativeName, isSelected && styles.nativeNameSelected]}>
                          {item.nativeName}
                        </Text>
                        <Text style={styles.englishName}>{item.name}</Text>
                      </View>
                    </View>

                    {isSelected ? (
                      <View style={styles.checkBadge}>
                        <Text style={styles.checkText}>✓</Text>
                      </View>
                    ) : (
                      <View style={styles.radioEmpty} />
                    )}
                  </TouchableOpacity>
                );
              }}
            />
          </View>
        </View>
      </Modal>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'flex-end',
  },
  backdropTouch: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetContainer: {
    backgroundColor: '#1E1E2D',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 24,
  },
  handleBar: {
    width: 44,
    height: 5,
    backgroundColor: '#374151',
    borderRadius: 3,
    alignSelf: 'center',
    marginBottom: 14,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  sheetSubtitle: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#2A2A3E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeBtnText: {
    color: '#9CA3AF',
    fontSize: 15,
    fontWeight: '700',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#262638',
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 44,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#374151',
  },
  searchIcon: {
    fontSize: 15,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 14,
  },
  clearSearch: {
    color: '#9CA3AF',
    fontSize: 14,
    padding: 4,
  },
  listContent: {
    paddingBottom: 10,
  },
  langItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#262638',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  langItemSelected: {
    backgroundColor: 'rgba(99, 102, 241, 0.15)',
    borderColor: '#6366F1',
  },
  langLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  flagIcon: {
    fontSize: 26,
  },
  nativeName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  nativeNameSelected: {
    color: '#818CF8',
  },
  englishName: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 1,
  },
  checkBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  radioEmpty: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#4B5563',
  },
});
